<?php

/** @var ResetButton $block */

/** @var \Magento\Framework\Escaper $escaper */

use HK2\Csp\Block\Adminhtml\System\Config\ResetButton;

?>

<?= $block->getButtonHtml(); ?>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm'
    ], function ($, confirm) {

        $('#cspwhitelisting_reset_button').on('click', function () {
            confirm({
                title: '<?= $escaper->escapeJs(__('Reset CSP')) ?>',
                content: '<?= $escaper->escapeJs(__('Clear all CSP fields and restore defaults. Continue?')) ?>',
                actions: {
                    confirm: function () {

                        clearCspFields();

                        window.location.href = '<?= $escaper->escapeUrl($block->getResetUrl()) ?>';
                    }
                }
            });
        });

        function clearCspFields() {
            const fields = [
                'script_src',
                'style_src',
                'img_src',
                'connect_src',
                'font_src',
                'frame_src'
            ];

            fields.forEach(function (field) {
                $('[data-ui-id$="' + field + '"]').val('');
            });
        }
    });
</script>
